In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('/content/employees_pandas_practice.csv')
first_5rows = df.head(5)
print(first_5rows)

   Employee_ID           Name  Age  Gender  Department             Job_Role  \
0            1  Aditya Sharma   38    Male   Marketing  Marketing Executive
1            2    Tanya Patel   55  Female   Marketing    Marketing Manager
2            3    Akash Joshi   27  Female  Operations   Operations Manager
3            4    Varun Patel   25    Male   Marketing    Marketing Manager
4            5   Ishaan Gupta   31    Male     Finance      Finance Manager

   Salary  Experience_Years        City Joining_Date  Performance_Score  \
0  114000                16  Chandigarh   2022-08-19                8.0
1  128000                25      Mumbai   2023-11-03                8.0
2   70000                 4       Noida   2017-05-30                8.0
3   59000                 3  Chandigarh   2020-04-09                8.0
4  106000                14         NaN   2018-06-22                8.0

     Bonus Education
0      NaN    B.Tech
1  12800.0    M.Tech
2   3500.0       MCA
3   7080.0       BBA
4   5300.0     B.Com

In [ ]:
last_rows = df.tail(10)
print(last_rows)

    Employee_ID           Name  Age  Gender        Department  \
90           91   Rahul Khanna   54    Male        Operations
91           92   Anika Mishra   45  Female             Sales
92           93     Yash Gupta   40  Female        Operations
93           94     Esha Mehta   29    Male                HR
94           95   Chetan Yadav   32    Male  Customer Support
95           96    Karan Ahuja   33  Female  Customer Support
96           97   Ananya Ahuja   44    Male                HR
97           98  Manish Sharma   47    Male      Data Science
98           99   Chetan Kumar   23  Female  Customer Support
99          100    Pooja Singh   39    Male             Sales

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
90     Operations Manager  141000                25      Jaipur   2024-09-11
91        Sales Executive  129000                25    Gurugram   2023-06-15
92     Operations Analyst  117000                18       Noida   2020-01-26
93             HR Manager   74000                 7       Noida   2025-05-17
94     Support Specialist   91000                15   Bengaluru   2020-12-28
95        Support Manager   88000                14       Noida   2021-12-04
96             HR Manager  115000                22   Hyderabad   2021-01-18
97  Senior Data Scientist  166000                25  Chandigarh   2020-03-19
98     Support Specialist   66000                 7    Gurugram   2016-01-26
99        Sales Executive  102000                16      Jaipur   2023-03-06

    Performance_Score    Bonus Education
90                8.0      NaN       MCA
91                7.0  12900.0       MBA
92                5.0  11700.0      B.Sc
93                9.0   3700.0      M.Sc
94               10.0   9100.0       BBA
95                8.0   7040.0     B.Com
96                9.0   9200.0      B.Sc
97                7.0   8300.0       MCA
98                6.0   3300.0       PhD
99               10.0  12240.0       PhD

In [9]:
columns = df.columns
print(columns)

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'Job_Role',
       'Salary', 'Experience_Years', 'City', 'Joining_Date',
       'Performance_Score', 'Bonus', 'Education'],
      dtype='object')

In [10]:
df.dtypes

Employee_ID            int64
Name                  object
Age                    int64
Gender                object
Department            object
Job_Role              object
Salary                 int64
Experience_Years       int64
City                  object
Joining_Date          object
Performance_Score    float64
Bonus                float64
Education             object
dtype: object

In [14]:
df.describe()

,Employee_ID,Age,Salary,Experience_Years,Performance_Score,Bonus
count,100.000000,100.000000,100.000000,100.000000,96.000000,93.000000
mean,50.500000,38.940000,111870.000000,17.230000,7.791667,9793.010753
std,29.011492,11.204995,30552.043692,7.692125,1.337056,4227.120200
min,1.000000,21.000000,43000.000000,0.000000,5.000000,2400.000000
25%,25.750000,30.000000,88000.000000,12.000000,7.000000,6600.000000
50%,50.500000,38.000000,116500.000000,18.000000,8.000000,9720.000000
75%,75.250000,48.000000,133000.000000,25.000000,9.000000,12300.000000
max,100.000000,58.000000,170000.000000,25.000000,10.000000,22200.000000

In [17]:
elements = df.size
print("total number of elements:",elements)

total number of elements: 1300

In [20]:
null_values = df.isnull().values.any()
print(null_values)

True

In [28]:
columns = df[['Name','Department','Salary']]
print(columns)

             Name        Department  Salary
0   Aditya Sharma         Marketing  114000
1     Tanya Patel         Marketing  128000
2     Akash Joshi        Operations   70000
3     Varun Patel         Marketing   59000
4    Ishaan Gupta           Finance  106000
..            ...               ...     ...
95    Karan Ahuja  Customer Support   88000
96   Ananya Ahuja                HR  115000
97  Manish Sharma      Data Science  166000
98   Chetan Kumar  Customer Support   66000
99    Pooja Singh             Sales  102000

[100 rows x 3 columns]

In [33]:
print(df[df['Employee_ID'] == 105])

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, Department, Job_Role, Salary, Experience_Years, City, Joining_Date, Performance_Score, Bonus, Education]
Index: []

In [35]:
print(df.iloc[0:10])

   Employee_ID             Name  Age  Gender  Department             Job_Role  \
0            1    Aditya Sharma   38    Male   Marketing  Marketing Executive
1            2      Tanya Patel   55  Female   Marketing    Marketing Manager
2            3      Akash Joshi   27  Female  Operations   Operations Manager
3            4      Varun Patel   25    Male   Marketing    Marketing Manager
4            5     Ishaan Gupta   31    Male     Finance      Finance Manager
5            6      Arjun Patel   57  Female   Marketing    Marketing Manager
6            7      Vikas Joshi   44    Male     Finance      Finance Manager
7            8  Shreya Malhotra   56    Male          HR           HR Manager
8            9      Diya Khanna   27  Female   Marketing  Marketing Executive
9           10      Karan Mehta   24    Male          HR         HR Executive

   Salary  Experience_Years        City Joining_Date  Performance_Score  \
0  114000                16  Chandigarh   2022-08-19                8.0
1  128000                25      Mumbai   2023-11-03                8.0
2   70000                 4       Noida   2017-05-30                8.0
3   59000                 3  Chandigarh   2020-04-09                8.0
4  106000                14         NaN   2018-06-22                8.0
5  143000                25      Mumbai   2018-12-24                7.0
6  127000                22  Chandigarh   2017-09-22                7.0
7  124000                25   Hyderabad   2020-11-19                7.0
8   77000                 9       Noida   2024-09-28                9.0
9   63000                 8       Noida   2024-08-06                7.0

     Bonus Education
0      NaN    B.Tech
1  12800.0    M.Tech
2   3500.0       MCA
3   7080.0       BBA
4   5300.0     B.Com
5  11440.0      M.Sc
6  15240.0      B.Sc
7      NaN       PhD
8   3850.0       MCA
9   5040.0       PhD
   Employee_ID             Name  Age  Gender  Department             Job_Role  \
0            1    Aditya Sharma   38    Male   Marketing  Marketing Executive
1            2      Tanya Patel   55  Female   Marketing    Marketing Manager
2            3      Akash Joshi   27  Female  Operations   Operations Manager
3            4      Varun Patel   25    Male   Marketing    Marketing Manager
4            5     Ishaan Gupta   31    Male     Finance      Finance Manager
5            6      Arjun Patel   57  Female   Marketing    Marketing Manager
6            7      Vikas Joshi   44    Male     Finance      Finance Manager
7            8  Shreya Malhotra   56    Male          HR           HR Manager
8            9      Diya Khanna   27  Female   Marketing  Marketing Executive
9           10      Karan Mehta   24    Male          HR         HR Executive

   Salary  Experience_Years        City Joining_Date  Performance_Score  \
0  114000                16  Chandigarh   2022-08-19                8.0
1  128000                25      Mumbai   2023-11-03                8.0
2   70000                 4       Noida   2017-05-30                8.0
3   59000                 3  Chandigarh   2020-04-09                8.0
4  106000                14         NaN   2018-06-22                8.0
5  143000                25      Mumbai   2018-12-24                7.0
6  127000                22  Chandigarh   2017-09-22                7.0
7  124000                25   Hyderabad   2020-11-19                7.0
8   77000                 9       Noida   2024-09-28                9.0
9   63000                 8       Noida   2024-08-06                7.0

     Bonus Education
0      NaN    B.Tech
1  12800.0    M.Tech
2   3500.0       MCA
3   7080.0       BBA
4   5300.0     B.Com
5  11440.0      M.Sc
6  15240.0      B.Sc
7      NaN       PhD
8   3850.0       MCA
9   5040.0       PhD

In [36]:
print(df[20:31])

    Employee_ID            Name  Age  Gender        Department  \
20           21     Isha Khanna   52  Female                IT
21           22    Pooja Mishra   21    Male                HR
22           23    Manish Patel   36    Male        Operations
23           24  Harsh Malhotra   31    Male      Data Science
24           25      Esha Joshi   42  Female                HR
25           26  Vikas Malhotra   23    Male      Data Science
26           27    Aarav Khanna   55    Male        Operations
27           28     Tanya Kumar   33  Female      Data Science
28           29      Riya Arora   49    Male  Customer Support
29           30    Gaurav Patel   30    Male                IT
30           31   Chetan Sharma   27  Female         Marketing

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
20      Software Engineer  149000                25       Delhi   2016-01-19
21           HR Executive   45000                 0    Gurugram   2022-03-17
22     Operations Manager  101000                15      Mumbai   2024-12-24
23         Data Scientist  125000                15   Bengaluru   2025-03-02
24             HR Manager  133000                24      Jaipur   2023-08-19
25  Senior Data Scientist   97000                 5    Gurugram   2021-09-29
26     Operations Manager  139000                25    Gurugram   2019-07-13
27         Data Scientist  128000                14       Noida   2025-05-11
28     Support Specialist  123000                25       Noida   2023-06-16
29      Software Engineer  122000                14  Chandigarh   2021-02-12
30    Marketing Executive   81000                11       Noida   2018-10-21

    Performance_Score    Bonus Education
20                8.0  11920.0       PhD
21                7.0   5400.0    B.Tech
22                7.0      NaN      M.Sc
23                9.0  12500.0    B.Tech
24                9.0  13300.0       MBA
25                6.0  11640.0      M.Sc
26                6.0  13900.0     B.Com
27                5.0  12800.0       MCA
28               10.0  12300.0     B.Com
29                8.0  18300.0       BBA
30                6.0   9720.0       PhD

In [39]:
highest_salary = df['Salary'].max()
print("highest_salary is :", highest_salary)

highest_salary is : 170000

In [40]:
lowest_salary = df['Salary'].min()
print("lowest_salary is :", lowest_salary)

lowest_salary is : 43000

In [ ]:
salary_greater = df[df['Salary'] > 50000]
print(salary_greater)

In [44]:
experience = df[df['Experience_Years'] > 5]
print("people have expericence more than five are :" ,experience)

people have expericence more than five are :     Employee_ID           Name  Age  Gender        Department  \
0             1  Aditya Sharma   38    Male         Marketing
1             2    Tanya Patel   55  Female         Marketing
4             5   Ishaan Gupta   31    Male           Finance
5             6    Arjun Patel   57  Female         Marketing
6             7    Vikas Joshi   44    Male           Finance
..          ...            ...  ...     ...               ...
95           96    Karan Ahuja   33  Female  Customer Support
96           97   Ananya Ahuja   44    Male                HR
97           98  Manish Sharma   47    Male      Data Science
98           99   Chetan Kumar   23  Female  Customer Support
99          100    Pooja Singh   39    Male             Sales

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
0     Marketing Executive  114000                16  Chandigarh   2022-08-19
1       Marketing Manager  128000                25      Mumbai   2023-11-03
4         Finance Manager  106000                14         NaN   2018-06-22
5       Marketing Manager  143000                25      Mumbai   2018-12-24
6         Finance Manager  127000                22  Chandigarh   2017-09-22
..                    ...     ...               ...         ...          ...
95        Support Manager   88000                14       Noida   2021-12-04
96             HR Manager  115000                22   Hyderabad   2021-01-18
97  Senior Data Scientist  166000                25  Chandigarh   2020-03-19
98     Support Specialist   66000                 7    Gurugram   2016-01-26
99        Sales Executive  102000                16      Jaipur   2023-03-06

    Performance_Score    Bonus Education
0                 8.0      NaN    B.Tech
1                 8.0  12800.0    M.Tech
4                 8.0   5300.0     B.Com
5                 7.0  11440.0      M.Sc
6                 7.0  15240.0      B.Sc
..                ...      ...       ...
95                8.0   7040.0     B.Com
96                9.0   9200.0      B.Sc
97                7.0   8300.0       MCA
98                6.0   3300.0       PhD
99               10.0  12240.0       PhD

[89 rows x 13 columns]

In [53]:
id_department = df[df['Department'] == 'IT']
print(id_department)

    Employee_ID          Name  Age  Gender Department  \
11           12   Vikas Mehta   21    Male         IT
20           21   Isha Khanna   52  Female         IT
29           30  Gaurav Patel   30    Male         IT
51           52    Varun Rana   22  Female         IT
64           65   Aditi Joshi   38    Male         IT
65           66   Anika Verma   40  Female         IT
67           68  Tanya Chopra   26  Female         IT
88           89   Karan Arora   49    Male         IT

                    Job_Role  Salary  Experience_Years        City  \
11         Software Engineer   54000                 0        Pune
20         Software Engineer  149000                25       Delhi
29         Software Engineer  122000                14  Chandigarh
51         Software Engineer   91000                 6     Kolkata
64  Senior Software Engineer  127000                19    Gurugram
65  Senior Software Engineer  122000                19   Hyderabad
67  Senior Software Engineer   81000                 4        Pune
88  Senior Software Engineer  143000                25  Chandigarh

   Joining_Date  Performance_Score    Bonus Education
11   2016-10-21                9.0   4320.0      B.Sc
20   2016-01-19                8.0  11920.0       PhD
29   2021-02-12                8.0  18300.0       BBA
51   2026-04-14                8.0   7280.0    M.Tech
64   2025-01-01                8.0  10160.0       MBA
65   2019-09-04                8.0   9760.0       MCA
67   2023-07-22                8.0  12150.0       BBA
88   2022-11-28               10.0  21450.0    B.Tech

In [58]:
emp_from = df[df['City'] .isin (['Delhi','Chandigarh'])]
print(emp_from)

    Employee_ID           Name  Age  Gender        Department  \
0             1  Aditya Sharma   38    Male         Marketing
3             4    Varun Patel   25    Male         Marketing
6             7    Vikas Joshi   44    Male           Finance
16           17  Sameer Khanna   31    Male                HR
19           20    Zoya Khanna   21  Female                HR
20           21    Isha Khanna   52  Female                IT
29           30   Gaurav Patel   30    Male                IT
32           33    Rahul Gupta   39    Male             Sales
38           39  Deepak Kapoor   27    Male             Sales
42           43    Akash Mehta   47  Female         Marketing
50           51    Rahul Singh   50  Female      Data Science
53           54     Riya Gupta   41  Female        Operations
54           55    Rahul Verma   34  Female           Finance
60           61    Kavya Ahuja   55    Male                HR
62           63    Sakshi Rana   30    Male  Customer Support
66           67  Shreya Khanna   38    Male             Sales
72           73    Yash Sharma   38    Male           Finance
76           77    Pooja Arora   35  Female        Operations
85           86    Meera Gupta   48    Male         Marketing
87           88   Sakshi Arora   57  Female        Operations
88           89    Karan Arora   49    Male                IT
89           90     Rahul Rana   33  Female  Customer Support
97           98  Manish Sharma   47    Male      Data Science

                    Job_Role  Salary  Experience_Years        City  \
0        Marketing Executive  114000                16  Chandigarh
3          Marketing Manager   59000                 3  Chandigarh
6            Finance Manager  127000                22  Chandigarh
16              HR Executive   83000                 9  Chandigarh
19              HR Executive   43000                 2  Chandigarh
20         Software Engineer  149000                25       Delhi
29         Software Engineer  122000                14  Chandigarh
32             Sales Manager  130000                21  Chandigarh
38             Sales Manager   80000                10  Chandigarh
42         Marketing Manager  143000                25       Delhi
50     Senior Data Scientist  167000                25  Chandigarh
53        Operations Analyst  141000                24       Delhi
54           Finance Manager  127000                18  Chandigarh
60              HR Executive  127000                25  Chandigarh
62           Support Manager   84000                14       Delhi
66             Sales Manager  116000                19  Chandigarh
72           Finance Manager  112000                17       Delhi
76        Operations Manager  117000                18  Chandigarh
85         Marketing Manager  145000                25  Chandigarh
87        Operations Manager  142000                25  Chandigarh
88  Senior Software Engineer  143000                25  Chandigarh
89        Support Specialist   76000                10  Chandigarh
97     Senior Data Scientist  166000                25  Chandigarh

   Joining_Date  Performance_Score    Bonus Education
0    2022-08-19                8.0      NaN    B.Tech
3    2020-04-09                8.0   7080.0       BBA
6    2017-09-22                7.0  15240.0      B.Sc
16   2023-08-01                7.0   9960.0    B.Tech
19   2024-05-02                9.0   3440.0       BBA
20   2016-01-19                8.0  11920.0       PhD
29   2021-02-12                8.0  18300.0       BBA
32   2017-07-24                7.0  10400.0      M.Sc
38   2022-08-26                7.0   4000.0    M.Tech
42   2017-01-20                8.0  11440.0       MCA
50   2022-09-19                NaN  20040.0       BBA
53   2023-05-21                9.0  16920.0      B.Sc
54   2016-05-02                NaN  10160.0      M.Sc
60   2020-11-16                6.0   6350.0    B.Tech
62   2026-02-02                9.0   8400.0       MCA
66   2021-04-06                6.0   9280.0      M.Sc
72   2017-06-27                5.0  11200.0       MBA
76   2019-07-08                8.0  11700.0      B.Sc
85   2020-06-13                8.0  14500.0    M.Tech
87   2021-04-08                9.0  14200.0    M.Tech
88   2022-11-28               10.0  21450.0    B.Tech
89   2025-02-07                8.0   3800.0      B.Sc
97   2020-03-19                7.0   8300.0       MCA

In [85]:
print(df[df['Salary'].between(40000, 80000)])

    Employee_ID           Name  Age  Gender        Department  \
2             3    Akash Joshi   27  Female        Operations
3             4    Varun Patel   25    Male         Marketing
8             9    Diya Khanna   27  Female         Marketing
9            10    Karan Mehta   24    Male                HR
11           12    Vikas Mehta   21    Male                IT
19           20    Zoya Khanna   21  Female                HR
21           22   Pooja Mishra   21    Male                HR
37           38    Harsh Patel   22    Male         Marketing
38           39  Deepak Kapoor   27    Male             Sales
71           72    Akash Patel   22    Male        Operations
74           75    Karan Arora   22    Male  Customer Support
80           81    Arjun Kumar   22    Male         Marketing
83           84   Jatin Bansal   28    Male  Customer Support
84           85  Abhinav Sethi   22  Female                HR
89           90     Rahul Rana   33  Female  Customer Support
93           94     Esha Mehta   29    Male                HR
98           99   Chetan Kumar   23  Female  Customer Support

               Job_Role  Salary  Experience_Years        City Joining_Date  \
2    Operations Manager   70000                 4       Noida   2017-05-30
3     Marketing Manager   59000                 3  Chandigarh   2020-04-09
8   Marketing Executive   77000                 9       Noida   2024-09-28
9          HR Executive   63000                 8       Noida   2024-08-06
11    Software Engineer   54000                 0        Pune   2016-10-21
19         HR Executive   43000                 2  Chandigarh   2024-05-02
21         HR Executive   45000                 0    Gurugram   2022-03-17
37  Marketing Executive   65000                 6    Gurugram   2026-08-22
38        Sales Manager   80000                10  Chandigarh   2022-08-26
71   Operations Analyst   63000                 1   Bengaluru   2016-10-12
74      Support Manager   48000                 5     Kolkata   2023-12-31
80    Marketing Manager   73000                 5        Pune   2017-10-10
83      Support Manager   55000                 7      Jaipur   2021-12-25
84           HR Manager   69000                 5         NaN   2023-12-20
89   Support Specialist   76000                10  Chandigarh   2025-02-07
93           HR Manager   74000                 7       Noida   2025-05-17
98   Support Specialist   66000                 7    Gurugram   2016-01-26

    Performance_Score   Bonus Education
2                 8.0  3500.0       MCA
3                 8.0  7080.0       BBA
8                 9.0  3850.0       MCA
9                 7.0  5040.0       PhD
11                9.0  4320.0      B.Sc
19                9.0  3440.0       BBA
21                7.0  5400.0    B.Tech
37                7.0  7800.0    M.Tech
38                7.0  4000.0    M.Tech
71                9.0  5040.0       MBA
74                9.0  2400.0       MBA
80                8.0  7300.0    M.Tech
83                7.0  8250.0      M.Sc
84                8.0  6900.0      B.Sc
89                8.0  3800.0      B.Sc
93                9.0  3700.0      M.Sc
98                6.0  3300.0       PhD

In [90]:
print(df[(df['Performance_Score'] > 8) & (df['Experience_Years'] > 3)])

    Employee_ID            Name  Age  Gender        Department  \
8             9     Diya Khanna   27  Female         Marketing
12           13     Harsh Ahuja   47    Male                HR
13           14   Kritika Singh   36    Male         Marketing
15           16      Isha Arora   39  Female  Customer Support
23           24  Harsh Malhotra   31    Male      Data Science
24           25      Esha Joshi   42  Female                HR
28           29      Riya Arora   49    Male  Customer Support
33           34   Pankaj Bansal   55  Female      Data Science
35           36      Riya Kumar   55    Male      Data Science
39           40     Varun Verma   43  Female        Operations
45           46   Ananya Mishra   39    Male  Customer Support
47           48    Shreya Joshi   49  Female             Sales
52           53    Rohan Chopra   47  Female        Operations
53           54      Riya Gupta   41  Female        Operations
61           62     Kavya Verma   39  Female        Operations
62           63     Sakshi Rana   30    Male  Customer Support
73           74      Isha Verma   29  Female                HR
74           75     Karan Arora   22    Male  Customer Support
77           78     Arjun Gupta   26    Male      Data Science
81           82    Ananya Kumar   31    Male                HR
87           88    Sakshi Arora   57  Female        Operations
88           89     Karan Arora   49    Male                IT
93           94      Esha Mehta   29    Male                HR
94           95    Chetan Yadav   32    Male  Customer Support
96           97    Ananya Ahuja   44    Male                HR
99          100     Pooja Singh   39    Male             Sales

                    Job_Role  Salary  Experience_Years        City  \
8        Marketing Executive   77000                 9       Noida
12              HR Executive  132000                25      Jaipur
13         Marketing Manager  107000                15      Mumbai
15        Support Specialist  103000                19   Bengaluru
23            Data Scientist  125000                15   Bengaluru
24                HR Manager  133000                24      Jaipur
28        Support Specialist  123000                25       Noida
33            Data Scientist  167000                25      Jaipur
35            Data Scientist  167000                25      Mumbai
39        Operations Analyst  128000                25      Jaipur
45        Support Specialist  101000                16   Hyderabad
47             Sales Manager  145000                25    Gurugram
52        Operations Analyst  139000                25      Jaipur
53        Operations Analyst  141000                24       Delhi
61        Operations Manager  112000                18       Noida
62           Support Manager   84000                14       Delhi
73              HR Executive   93000                13        Pune
74           Support Manager   48000                 5     Kolkata
77            Data Scientist   98000                 8       Noida
81                HR Manager   99000                15     Kolkata
87        Operations Manager  142000                25  Chandigarh
88  Senior Software Engineer  143000                25  Chandigarh
93                HR Manager   74000                 7       Noida
94        Support Specialist   91000                15   Bengaluru
96                HR Manager  115000                22   Hyderabad
99           Sales Executive  102000                16      Jaipur

   Joining_Date  Performance_Score    Bonus Education
8    2024-09-28                9.0   3850.0       MCA
12   2020-08-14                9.0   6600.0      M.Sc
13   2019-02-18                9.0   8560.0       PhD
15   2016-08-31               10.0  15450.0      B.Sc
23   2025-03-02                9.0  12500.0    B.Tech
24   2023-08-19                9.0  13300.0       MBA
28   2023-06-16               10.0  12300.0     B.Com
33   2026-02-27               10.0   8350.0    B.Tech
35   2025-09-24                9.0      NaN       MCA
39   2025-03-26                9.0   6400.0      B.Sc
45   2021-04-10                9.0  12120.0      B.Sc
47   2016-09-07               10.0   7250.0    M.Tech
52   2023-10-16                9.0  13900.0    B.Tech
53   2023-05-21                9.0  16920.0      B.Sc
61   2020-08-18               10.0   8960.0       BBA
62   2026-02-02                9.0   8400.0       MCA
73   2021-10-07               10.0   4650.0       PhD
74   2023-12-31                9.0   2400.0       MBA
77   2016-09-06               10.0  14700.0      M.Sc
81   2022-10-26                9.0  11880.0      M.Sc
87   2021-04-08                9.0  14200.0    M.Tech
88   2022-11-28               10.0  21450.0    B.Tech
93   2025-05-17                9.0   3700.0      M.Sc
94   2020-12-28               10.0   9100.0       BBA
96   2021-01-18                9.0   9200.0      B.Sc
99   2023-03-06               10.0  12240.0       PhD

In [91]:
print(df[df['Name'].str.startswith('A')])

    Employee_ID            Name  Age  Gender        Department  \
0             1   Aditya Sharma   38    Male         Marketing
2             3     Akash Joshi   27  Female        Operations
5             6     Arjun Patel   57  Female         Marketing
14           15     Anika Verma   55    Male                HR
26           27    Aarav Khanna   55    Male        Operations
42           43     Akash Mehta   47  Female         Marketing
45           46   Ananya Mishra   39    Male  Customer Support
46           47    Aditya Gupta   46  Female                HR
49           50     Arjun Mehta   37    Male      Data Science
55           56     Akash Mehta   28  Female                HR
59           60     Aarav Kumar   47    Male                HR
64           65     Aditi Joshi   38    Male                IT
65           66     Anika Verma   40  Female                IT
70           71  Abhinav Chopra   34  Female  Customer Support
71           72     Akash Patel   22    Male        Operations
77           78     Arjun Gupta   26    Male      Data Science
78           79   Ananya Kapoor   40  Female                HR
80           81     Arjun Kumar   22    Male         Marketing
81           82    Ananya Kumar   31    Male                HR
82           83   Aditya Kapoor   58  Female             Sales
84           85   Abhinav Sethi   22  Female                HR
91           92    Anika Mishra   45  Female             Sales
96           97    Ananya Ahuja   44    Male                HR

                    Job_Role  Salary  Experience_Years        City  \
0        Marketing Executive  114000                16  Chandigarh
2         Operations Manager   70000                 4       Noida
5          Marketing Manager  143000                25      Mumbai
14              HR Executive  133000                25     Kolkata
26        Operations Manager  139000                25    Gurugram
42         Marketing Manager  143000                25       Delhi
45        Support Specialist  101000                16   Hyderabad
46              HR Executive  125000                25    Gurugram
49            Data Scientist  130000                17   Hyderabad
55              HR Executive   84000                12       Noida
59                HR Manager  131000                25    Gurugram
64  Senior Software Engineer  127000                19    Gurugram
65  Senior Software Engineer  122000                19   Hyderabad
70        Support Specialist   86000                16        Pune
71        Operations Analyst   63000                 1   Bengaluru
77            Data Scientist   98000                 8       Noida
78              HR Executive  115000                19   Bengaluru
80         Marketing Manager   73000                 5        Pune
81                HR Manager   99000                15     Kolkata
82           Sales Executive  139000                25    Gurugram
84                HR Manager   69000                 5         NaN
91           Sales Executive  129000                25    Gurugram
96                HR Manager  115000                22   Hyderabad

   Joining_Date  Performance_Score    Bonus Education
0    2022-08-19                8.0      NaN    B.Tech
2    2017-05-30                8.0   3500.0       MCA
5    2018-12-24                7.0  11440.0      M.Sc
14   2021-05-29                NaN  15960.0      M.Sc
26   2019-07-13                6.0  13900.0     B.Com
42   2017-01-20                8.0  11440.0       MCA
45   2021-04-10                9.0  12120.0      B.Sc
46   2026-08-27                8.0   6250.0       BBA
49   2025-04-12                7.0      NaN     B.Com
55   2023-12-03                8.0  10080.0       PhD
59   2023-10-12                8.0   6550.0      M.Sc
64   2025-01-01                8.0  10160.0       MBA
65   2019-09-04                8.0   9760.0       MCA
70   2022-02-12                8.0   4300.0      B.Sc
71   2016-10-12                9.0   5040.0       MBA
77   2016-09-06               10.0  14700.0      M.Sc
78   2025-07-06                6.0  11500.0       BBA
80   2017-10-10                8.0   7300.0    M.Tech
81   2022-10-26                9.0  11880.0      M.Sc
82   2016-08-16                5.0  11120.0     B.Com
84   2023-12-20                8.0   6900.0      B.Sc
91   2023-06-15                7.0  12900.0       MBA
96   2021-01-18                9.0   9200.0      B.Sc

In [89]:
descending_order = df.sort_values(by='Salary', ascending=False)
print(descending_order)

    Employee_ID           Name  Age  Gender        Department  \
75           76  Ishaan Saxena   58  Female      Data Science
43           44   Rohan Mishra   54  Female      Data Science
33           34  Pankaj Bansal   55  Female      Data Science
35           36     Riya Kumar   55    Male      Data Science
50           51    Rahul Singh   50  Female      Data Science
..          ...            ...  ...     ...               ...
83           84   Jatin Bansal   28    Male  Customer Support
11           12    Vikas Mehta   21    Male                IT
74           75    Karan Arora   22    Male  Customer Support
21           22   Pooja Mishra   21    Male                HR
19           20    Zoya Khanna   21  Female                HR

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
75  Senior Data Scientist  170000                25    Gurugram   2020-11-01
43  Senior Data Scientist  168000                25   Hyderabad   2019-06-13
33         Data Scientist  167000                25      Jaipur   2026-02-27
35         Data Scientist  167000                25      Mumbai   2025-09-24
50  Senior Data Scientist  167000                25  Chandigarh   2022-09-19
..                    ...     ...               ...         ...          ...
83        Support Manager   55000                 7      Jaipur   2021-12-25
11      Software Engineer   54000                 0        Pune   2016-10-21
74        Support Manager   48000                 5     Kolkata   2023-12-31
21           HR Executive   45000                 0    Gurugram   2022-03-17
19           HR Executive   43000                 2  Chandigarh   2024-05-02

    Performance_Score    Bonus Education
75                6.0   8500.0       BBA
43                8.0  13440.0       PhD
33               10.0   8350.0    B.Tech
35                9.0      NaN       MCA
50                NaN  20040.0       BBA
..                ...      ...       ...
83                7.0   8250.0      M.Sc
11                9.0   4320.0      B.Sc
74                9.0   2400.0       MBA
21                7.0   5400.0    B.Tech
19                9.0   3440.0       BBA

[100 rows x 13 columns]

In [95]:
print(df.sort_values(by=['Department', 'Salary'], ascending=[True, False]))

    Employee_ID           Name  Age  Gender        Department  \
31           32    Yash Bansal   49  Female  Customer Support
63           64   Vikas Kapoor   48  Female  Customer Support
28           29     Riya Arora   49    Male  Customer Support
15           16     Isha Arora   39  Female  Customer Support
45           46  Ananya Mishra   39    Male  Customer Support
..          ...            ...  ...     ...               ...
66           67  Shreya Khanna   38    Male             Sales
10           11     Yash Sethi   34    Male             Sales
99          100    Pooja Singh   39    Male             Sales
44           45     Diya Patel   34  Female             Sales
38           39  Deepak Kapoor   27    Male             Sales

              Job_Role  Salary  Experience_Years        City Joining_Date  \
31  Support Specialist  129000                25   Hyderabad   2024-06-10
63     Support Manager  127000                25     Kolkata   2017-03-16
28  Support Specialist  123000                25       Noida   2023-06-16
15  Support Specialist  103000                19   Bengaluru   2016-08-31
45  Support Specialist  101000                16   Hyderabad   2021-04-10
..                 ...     ...               ...         ...          ...
66       Sales Manager  116000                19  Chandigarh   2021-04-06
10       Sales Manager  109000                16       Noida   2021-01-27
99     Sales Executive  102000                16      Jaipur   2023-03-06
44       Sales Manager   87000                12   Hyderabad   2018-07-24
38       Sales Manager   80000                10  Chandigarh   2022-08-26

    Performance_Score    Bonus Education
31                7.0  12900.0     B.Com
63                7.0  15240.0     B.Com
28               10.0  12300.0     B.Com
15               10.0  15450.0      B.Sc
45                9.0  12120.0      B.Sc
..                ...      ...       ...
66                6.0   9280.0      M.Sc
10                6.0   8720.0       BBA
99               10.0  12240.0       PhD
44                8.0   6960.0    B.Tech
38                7.0   4000.0    M.Tech

[100 rows x 13 columns]

In [96]:
print(df.sort_values(by='Salary', ascending=False).head(5))

    Employee_ID           Name  Age  Gender    Department  \
75           76  Ishaan Saxena   58  Female  Data Science
43           44   Rohan Mishra   54  Female  Data Science
33           34  Pankaj Bansal   55  Female  Data Science
35           36     Riya Kumar   55    Male  Data Science
50           51    Rahul Singh   50  Female  Data Science

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
75  Senior Data Scientist  170000                25    Gurugram   2020-11-01
43  Senior Data Scientist  168000                25   Hyderabad   2019-06-13
33         Data Scientist  167000                25      Jaipur   2026-02-27
35         Data Scientist  167000                25      Mumbai   2025-09-24
50  Senior Data Scientist  167000                25  Chandigarh   2022-09-19

    Performance_Score    Bonus Education
75                6.0   8500.0       BBA
43                8.0  13440.0       PhD
33               10.0   8350.0    B.Tech
35                9.0      NaN       MCA
50                NaN  20040.0       BBA

In [97]:
print(df.isnull().sum())

Employee_ID          0
Name                 0
Age                  0
Gender               0
Department           0
Job_Role             0
Salary               0
Experience_Years     0
City                 2
Joining_Date         0
Performance_Score    4
Bonus                7
Education            0
dtype: int64

In [98]:
df['Bonus'] = df['Bonus'].fillna(0)
print(df)

    Employee_ID           Name  Age  Gender        Department  \
0             1  Aditya Sharma   38    Male         Marketing
1             2    Tanya Patel   55  Female         Marketing
2             3    Akash Joshi   27  Female        Operations
3             4    Varun Patel   25    Male         Marketing
4             5   Ishaan Gupta   31    Male           Finance
..          ...            ...  ...     ...               ...
95           96    Karan Ahuja   33  Female  Customer Support
96           97   Ananya Ahuja   44    Male                HR
97           98  Manish Sharma   47    Male      Data Science
98           99   Chetan Kumar   23  Female  Customer Support
99          100    Pooja Singh   39    Male             Sales

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
0     Marketing Executive  114000                16  Chandigarh   2022-08-19
1       Marketing Manager  128000                25      Mumbai   2023-11-03
2      Operations Manager   70000                 4       Noida   2017-05-30
3       Marketing Manager   59000                 3  Chandigarh   2020-04-09
4         Finance Manager  106000                14         NaN   2018-06-22
..                    ...     ...               ...         ...          ...
95        Support Manager   88000                14       Noida   2021-12-04
96             HR Manager  115000                22   Hyderabad   2021-01-18
97  Senior Data Scientist  166000                25  Chandigarh   2020-03-19
98     Support Specialist   66000                 7    Gurugram   2016-01-26
99        Sales Executive  102000                16      Jaipur   2023-03-06

    Performance_Score    Bonus Education
0                 8.0      0.0    B.Tech
1                 8.0  12800.0    M.Tech
2                 8.0   3500.0       MCA
3                 8.0   7080.0       BBA
4                 8.0   5300.0     B.Com
..                ...      ...       ...
95                8.0   7040.0     B.Com
96                9.0   9200.0      B.Sc
97                7.0   8300.0       MCA
98                6.0   3300.0       PhD
99               10.0  12240.0       PhD

[100 rows x 13 columns]

In [99]:
df['Total_Salary'] = df['Salary'] + df['Bonus']
print(df)

    Employee_ID           Name  Age  Gender        Department  \
0             1  Aditya Sharma   38    Male         Marketing
1             2    Tanya Patel   55  Female         Marketing
2             3    Akash Joshi   27  Female        Operations
3             4    Varun Patel   25    Male         Marketing
4             5   Ishaan Gupta   31    Male           Finance
..          ...            ...  ...     ...               ...
95           96    Karan Ahuja   33  Female  Customer Support
96           97   Ananya Ahuja   44    Male                HR
97           98  Manish Sharma   47    Male      Data Science
98           99   Chetan Kumar   23  Female  Customer Support
99          100    Pooja Singh   39    Male             Sales

                 Job_Role  Salary  Experience_Years        City Joining_Date  \
0     Marketing Executive  114000                16  Chandigarh   2022-08-19
1       Marketing Manager  128000                25      Mumbai   2023-11-03
2      Operations Manager   70000                 4       Noida   2017-05-30
3       Marketing Manager   59000                 3  Chandigarh   2020-04-09
4         Finance Manager  106000                14         NaN   2018-06-22
..                    ...     ...               ...         ...          ...
95        Support Manager   88000                14       Noida   2021-12-04
96             HR Manager  115000                22   Hyderabad   2021-01-18
97  Senior Data Scientist  166000                25  Chandigarh   2020-03-19
98     Support Specialist   66000                 7    Gurugram   2016-01-26
99        Sales Executive  102000                16      Jaipur   2023-03-06

    Performance_Score    Bonus Education  Total_Salary
0                 8.0      0.0    B.Tech      114000.0
1                 8.0  12800.0    M.Tech      140800.0
2                 8.0   3500.0       MCA       73500.0
3                 8.0   7080.0       BBA       66080.0
4                 8.0   5300.0     B.Com      111300.0
..                ...      ...       ...           ...
95                8.0   7040.0     B.Com       95040.0
96                9.0   9200.0      B.Sc      124200.0
97                7.0   8300.0       MCA      174300.0
98                6.0   3300.0       PhD       69300.0
99               10.0  12240.0       PhD      114240.0

[100 rows x 14 columns]

In [100]:
print(df.groupby('Department')['Salary'].mean())

Department
Customer Support     90866.666667
Data Science        143909.090909
Finance             123714.285714
HR                  100600.000000
IT                  111125.000000
Marketing           108461.538462
Operations          117285.714286
Sales               118500.000000
Name: Salary, dtype: float64

In [101]:
print(df.groupby('Department').agg(
    Total_Employees=('Employee_ID', 'count'),
    Average_Salary=('Salary', 'mean'),
    Maximum_Salary=('Salary', 'max'),
    Minimum_Salary=('Salary', 'min'),
    Average_Performance_Score=('Performance_Score', 'mean')
))

                  Total_Employees  Average_Salary  Maximum_Salary  \
Department
Customer Support               15    90866.666667          129000
Data Science                   11   143909.090909          170000
Finance                         7   123714.285714          148000
HR                             20   100600.000000          133000
IT                              8   111125.000000          149000
Marketing                      13   108461.538462          145000
Operations                     14   117285.714286          143000
Sales                          12   118500.000000          145000

                  Minimum_Salary  Average_Performance_Score
Department
Customer Support           48000                   8.200000
Data Science               97000                   7.700000
Finance                   106000                   7.200000
HR                         43000                   7.736842
IT                         54000                   8.375000
Marketing                  59000                   7.538462
Operations                 63000                   7.928571
Sales                      80000                   7.416667